<?php
declare(strict_types=1);

/**
 * Created by PhpStorm.
 * User: vanny
 * Date: 03.04.2018
 * Time: 18:43
 */

namespace app\module\admin\controllers;

use app\models\users\User;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

trait AdminTrait
{

    /**
     * @return array
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['logout'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function () {
                            return User::isUserTrainer(\Yii::$app->user->identity->email);
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @param $action
     * @return mixed
     */
    public function beforeAction($action)
    {
        \Yii::setAlias('@app\views\structure.php', \Yii::$app->basePath . '\module\admin\views\structure.php');
        if (\Yii::$app->user->identity->role !== User::ROLE_ADMIN) {
            if (static::className() === UserController::className())
                return $this->redirect(['/admin/default']);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @param $model
     */
    protected function showDump($model): void
    {
        foreach ($model as $key => $value) {
            echo $key . ": " . $value . "<br>";
        }
    }

}